### Import Libraries

In [37]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier



### Pre-Processing

##### Read Dataset

In [9]:
df = pd.read_csv("weather.csv",delimiter=";")
df.head()

outlook  temp humidity  windy play
0     rainy   hot     high  False   no
1     rainy   hot     high   True   no
2  overcast   hot     high  False  yes
3     sunny  mild     high  False  yes
4     sunny  cool   normal  False  yes

## Label Encouding

In [10]:
outlouk_enc = LabelEncoder()
temp_enc = LabelEncoder()
humidity_enc = LabelEncoder()
windy_enc = LabelEncoder()
play_enc = LabelEncoder()

df['outlook'] = outlouk_enc.fit_transform(df['outlook'])
df['temp'] = temp_enc.fit_transform(df['temp'])
df['humidity'] = humidity_enc.fit_transform(df['humidity'])
df['windy'] = windy_enc.fit_transform(df['windy'])
df['play'] = play_enc.fit_transform(df['play'])

In [11]:
df.head()

outlook  temp  humidity  windy  play
0        1     1         0      0     0
1        1     1         0      1     0
2        0     1         0      0     1
3        2     2         0      0     1
4        2     0         1      0     1

##### Shrink Columns|

In [23]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [24]:
x

array([[1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [2, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [2, 2, 1, 0],
       [1, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [2, 2, 0, 1]], dtype=int64)

##### Standardization

In [4]:
sc = StandardScaler()
x = sc.fit_transform(x)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


##### Split data to train & test set

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

### Model Building

In [43]:
clf = DecisionTreeClassifier()
clf.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [44]:
test = ["rainy","hot","high","False"]
test[0] = int(outlouk_enc.transform([test[0]]))
test[1] = int(temp_enc.transform([test[1]]))
test[2] = int(humidity_enc.transform([test[2]]))
test[3] = int(windy_enc.transform([test[3]]))
#print(test)

y_pred = clf.predict(np.array(test).reshape(1, -1))
play_enc.inverse_transform(y_pred)[0]

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


'no'

In [45]:
clf.feature_importances_

array([0.47111111, 0.        , 0.28      , 0.24888889])

In [41]:
clf = RandomForestClassifier(n_estimators=100)
clf.fit(x,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
y_pred = clf.predict(np.array(test).reshape(1, -1))
play_enc.inverse_transform(y_pred)[0]

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


'no'

### Evaluation

In [20]:
clf.score(x_test,y_test)

0.93

### Prediction

In [8]:
clf.predict(x_test)

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)